### ISSUE TITLE
pyxnat to xnatpy

### ISSUE THREAD

**Issue by mmodat** [VUIIS/dax#211]
@atbenmurray and I were discussing a potential change from pyxnat to xnatpy in order to be able to update dax to python 3.+.

@BennettLandman et al. Do you have any preference?

If not, we (aka Ben) could start looking into it to get an idea of the implication.
Let us know.

**Comment by BennettLandman** [comment]
@bud42 @justinblaber Moving to python3 definitely needs to be done. However, I am under the impression that the YAML migration is not in full stable release. 

While we consider migration, we need to be very careful with http overhead. We are working with several very large projects with many assessors. When the queries are not targeted precisely and/or not cache, the projects can take a very very very long time to traverse.

**Comment by bud42** [comment]
pyxnat was recently updated to work with python3. I've been working on a branch of dax for python3. @atbenmurray or anyone else is welcome to collaborate on it.
#206

**Comment by atbenmurray** [comment]
@BennettLandman Re: you still have performance issues? I'm very happy to look at any outstanding performance issues. Shall we schedule a chat to discuss specifics?

**Comment by atbenmurray** [comment]
@bud42 I haven't looked into the python3 port of pyxnat (I didn't know about it even). We were of the opinion that since we have to reach into internals of pyxnat in order to use it that it isn't particularly suitable for wrapping with more sophisticated caching mechanisms or mocking for testing, which is why we were considering xnatpy, which is somewhat more lightweight.

**Comment by BennettLandman** [comment]
@onealbao is working on performance issues with @KarthikMasi and @justinblaber

**Comment by mmodat** [comment]
Are you referring to performance issues related to http overhead when communicating with XNAT or anything related to the build/parsing of yaml processors.
If the latter, please keep us in the loop so that we can help as we were under the impression it was working fine.

**Comment by BennettLandman** [comment]
To the best of my knowledge, the overhead is mainly in the XNAT<-->DAX interface and the way pyxnat is used.

**Comment by atbenmurray** [comment]
@BennettLandman those two things and processor parser performance are quite closely linked. Since pyxnat doesn't cache, XNAT has its own caching mechanism in the form of the CachedImageSession/Scan/Assessor and CachedResource classes. These are very expensive still and must still be used very carefully. I had a larger set of changes in mind than the ones that I made in the initial instance, that involve recreating the caching mechanism and using more efficient XNAT queries. I'm happy to help on this.

**Comment by onealbao** [comment]
Hi @atbenmurray, I've found utilizing cache in pyxnat layer is straightforward, its all about 'Requests' HTTP library. I've figured out three potential ways to make the cache 
(1) requests-cache (https://github.com/reclosedev/requests-cache)
(2) cachecontrol (https://github.com/ionrock/cachecontrol) 
(3) pyxnat self defined cache mechanism (not recommend since the code seems to be not updated for a while)

My current findings are that project URL queries will dump all infos. And further session, subject, or experiment related queries response content can actually be retrieved from project queries. So we are thinking to keep project queries part, caching the results or storing them in some temporary place. And we skip lower layers' queries (which usually involves bottleneck). Please let me know if it works for you.

**Comment by atbenmurray** [comment]
If what I understand is correct, you are referring to making use of the parts of the rest api that allow you to fetch across multiple subjects and experiments. If so, that was also the essence of the approach that we were thinking about taking. We had thought about doing this through a caching mechanism that is capable of knowing what it has to request when we are constructing the query, as opposed to using more generic rest caching. That said, unless there is a performance issue, I can see how it might be a perfectly valid approach to just apply a rest request caching library.

**Comment by onealbao** [comment]
I totally agree with you that cache should be applied more intelligently. I am currently still focusing on dax_build performance, so only dax_build will use the caching library. The other part of dax function (i.e dax_upload, dax_dowload) will keep using regular rest URI query without caching. This should be a useful API.

**Comment by baxpr** [comment]
We're now at v1.3, still on pyxnat and I don't think we're having query/cache problems? Is this issue still relevant or should we close?

**Comment by baxpr** [comment]
We seem to be stable with pyxnat and python 3 in the main branch, and @onealbao has got some caching strategies that seem to be working in legacy version (https://github.com/VUIIS/LDax). So I'm closing this issue (but bring it back if need be)
