### ISSUE TITLE
XnatUtils.makedir shouldn't error if directory exists

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#71]
Traceback (most recent call last):
  File "/home/masispider/masimatlab/trunk/xnatspiders/spiders/Spider_dtiQA_v3_1_0.py", line 383, in <module>
    arguments=init_dtiQA(args)
  File "/home/masispider/masimatlab/trunk/xnatspiders/spiders/Spider_dtiQA_v3_1_0.py", line 49, in init_dtiQA
    arguments['jobdir'] = XnatUtils.makedir(os.path.abspath(options.tempdir))
  File "/home/masispider/.local/lib/python2.7/site-packages/dax-0.4.0-py2.7.egg/dax/XnatUtils.py", line 1533, in makedir
    os.mkdir(directory)
OSError: [Errno 17] File exists: '/tmp/XXXXXX-x-XXXXXXXX-x-XXXXXXX-x-DTI2-x-dtiQA_v3'

**Comment by damonms** [comment]
https://github.com/VUIIS/dax/pull/81

**Comment by byvernault** [comment]
This error is weird. In the code, it should have create a TempFolder_date to host the new data for this job and not error with OSError. Since there is a if not os.path.exists(dir): os.mkdir(path), it should not error if the folder exists. 

By changing, os.mkdir to os.makedirs, it's going to create the intermediate directories if they don't exist but it will error as well if the folder exists (see below). 

In [1]: direc = '/Users/byvernault/test/test/'

In [2]: import os

In [3]: os.maked
os.makedev   os.makedirs

In [3]: os.makedirs(direc)

In [4]: os.makedirs(direc)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-8139528cc239> in <module>()
----> 1 os.makedirs(direc)

/Users/byvernault/home-local/code/python/lib/python2.7/os.pyc in makedirs(name, mode)
    155         if tail == curdir:           # xxx/newdir/. exists if xxx/newdir exists
    156             return
--> 157     mkdir(name, mode)
    158
    159 def removedirs(name):

OSError: [Errno 17] File exists: '/Users/byvernault/test/test/'

In python 3, there is a variable exist_ok=False for os.makedirs, if it's set to True, it won't error. 

Could you reproduce this error? I wonder if it wasn't an old version of XnatUtils.

Cheers,

**Comment by damonms** [comment]
It's super weird. I agree it shouldn't have gotten an error. Either way, it's probably good to have it as makedirs so it can be used more generically. Thoughts?
